# Generated by Django 4.2.7 on 2023-11-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answerlike_questionlike_remove_answer_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelTable(
            name='answer',
            table=None,
        ),
    ]
