# Generated by Django 4.2.7 on 2023-11-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_answer_options_alter_answer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(default='all', max_length=20, unique=True),
        ),
    ]
