# Generated by Django 4.2.6 on 2023-12-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tag_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
